### ISSUE TITLE
primordials is not defined

### ISSUE THREAD

**Issue by lfender6445** [bluesmoon/node-geoip#175]
Trying to update the database with the following command and receiving this output

```
› node -v
v12.2.0
› node ./node_modules/geoip-lite/scripts/updatedb.js

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/lfender/source/ag.js/node_modules/geoip-lite/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/lfender/source/ag.js/node_modules/geoip-lite/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/lfender/source/ag.js/node_modules/geoip-lite/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
```

can anyone help and provide guidance? worth mentioning I am using recent node upgrade to 12

could be similar to https://github.com/gulpjs/gulp/issues/2324

**Comment by ar2rsawseen** [comment]
Yep, natives module is not supported by latest nodejs, which means we need to probably upgrade graceful js which does not use natives module.
Will try to check when I have time

**Comment by ar2rsawseen** [comment]
Hello,
so when installing this package clean, I see that it installs graceful-js version 4.1.15
which already has this fixed
so it seems your dependencies are out of date, reinstalling or running npm upgrade should fix this for you
Could this be the case?
