### ISSUE TITLE
updatedb returns getaddrinfo ENOTFOUND geolite.maxmind.com error

### ISSUE THREAD

**Issue by avilaviad** [bluesmoon/node-geoip#191]
Hi,
I'm trying to update the db using below steps but keep getting ENOTFOUND error (my current version is geoip-lite@1.3.8):
1. cd ./node_modules/geoip-lite
2. npm run-script updatedb license_key=#MY_LICENSE_KEY# (attached screenshot of license key page in MaxMind).
3. Error:
```
Checking  https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.md5
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND geolite.maxmind.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (_http_client.js:407:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'geolite.maxmind.com'
}
```

Am I missing something in the updatedb process?
<img width="717" alt="license" src="https://user-images.githubusercontent.com/1835750/73359578-02cf9280-4256-11ea-9e16-bab0bdf73dd8.png">

**Comment by avilaviad** [comment]
removing package and reinstalling the new version 1.4.0 fixed this issue.
