### ISSUE TITLE
_.padStart is not a function

### ISSUE THREAD

**Issue by jeerbl** [bluesmoon/node-geoip#192]
Hi,

I update to 1.4.0 and I now get this issue (I have a valid license key, replaced it by XXXXXXX in the logs I copied).

```
Step 8/11 : RUN node ./node_modules/geoip-lite/scripts/updatedb.js license_key=XXXXXXX
 ---> Running in 33a0d5dfac56
Checking  GeoLite2-Country-CSV.zip
Database country has new data
Fetching  GeoLite2-Country-CSV.zip
Retrieving GeoLite2-Country-CSV.zip ... DONE
Extracting GeoLite2-Country-CSV.zip ... DONE
Processing Lookup Data (may take a moment) ... DONE
Processing Data (may take a moment) .../var/www/app/node_modules/ip-address/lib/ipv4.js:306
  return _.padStart(this.bigInteger().toString(2), constants.BITS, '0');
           ^

TypeError: _.padStart is not a function
    at Address4.binaryZeroPad (/var/www/app/node_modules/ip-address/lib/ipv4.js:306:12)
    at Address4.getBitsBase2 (/var/www/app/node_modules/ip-address/lib/ipv4.js:288:15)
    at Address4.mask (/var/www/app/node_modules/ip-address/lib/ipv4.js:278:15)
    at Address4._startAddress (/var/www/app/node_modules/ip-address/lib/ipv4.js:193:10)
    at Address4.startAddress (/var/www/app/node_modules/ip-address/lib/ipv4.js:205:39)
    at processLine (/var/www/app/node_modules/geoip-lite/scripts/updatedb.js:369:26)
    at /var/www/app/node_modules/lazy/lazy.js:99:35
    at Lazy.<anonymous> (/var/www/app/node_modules/lazy/lazy.js:74:37)
    at emitTwo (events.js:106:13)
    at Lazy.emit (events.js:191:7)
```

I checked and the module `ip-address` updated to specific lodash libraries in [PR 92](https://github.com/beaugunderson/ip-address/pull/92).

Best,
Jerome

**Comment by jeerbl** [comment]
Would it be possible to update the `ip-address` dependency?

**Comment by jeerbl** [comment]
Bumped my lodash version to 4.* since `padStart` didn't exist in version 3, working now. Closing this.
